//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("GitTfs")]
[assembly: AssemblyProduct("GitTfs")]
[assembly: AssemblyVersion("0.29.46")]
[assembly: AssemblyFileVersion("0.29.46")]
[assembly: AssemblyInformationalVersion("0.29.46+5b8991f68c5302e279649e4c9bb99edd6ae98096.infinite_loop")]
[assembly: AssemblyCopyright("Copyright © 2009-2019")]

